config/routes.rb
Omrails::Application.routes.draw do

  resources :cts

  devise_for :users

get 'about' => 'pages#about'

  root :to => 'cts#index'

end

app/models/ct.rb
class Ct < ActiveRecord::Base
  attr_accessible :description, :image
  
  
  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
                             content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                             size: { less_than: 5.megabytes }
  
  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  
  has_many :cts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cts_controller.rb
class CtsController < ApplicationController
before_filter :authenticate_user!, except: [:index]

  # GET /cts
  # GET /cts.json
  def index
    @cts = Ct.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cts }
    end
  end

  # GET /cts/1
  # GET /cts/1.json
  def show
    @ct = Ct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ct }
    end
  end

  # GET /cts/new
  # GET /cts/new.json
  def new
    @ct = current_user.cts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ct }
    end
  end

  # GET /cts/1/edit
  def edit
    @ct = current_user.cts.find(params[:id])
  end

  # POST /cts
  # POST /cts.json
  def create
    @ct = current_user.cts.new(params[:ct])

    respond_to do |format|
      if @ct.save
        format.html { redirect_to @ct, notice: 'Ct was successfully created.' }
        format.json { render json: @ct, status: :created, location: @ct }
      else
        format.html { render action: "new" }
        format.json { render json: @ct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cts/1
  # PUT /cts/1.json
  def update
    @ct = current_user.cts.find(params[:id])

    respond_to do |format|
      if @ct.update_attributes(params[:ct])
        format.html { redirect_to @ct, notice: 'Ct was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cts/1
  # DELETE /cts/1.json
  def destroy
    @ct = current_user.cts.find(params[:id])
    @ct.destroy

    respond_to do |format|
      format.html { redirect_to cts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/c_ts_helper.rb
module CTsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cts/_ct.html.erb
<div class="box">
	<%= link_to (image_tag ct.image(:medium)), ct %>
	<p class="description">
		<%= ct.description %>
	</p>
	<p>
		<strong>
			Posted by <%= ct.user.name %>
		</strong>	
	</p>	

	<% if current_user == ct.user %>
		<p>
	  		<%= link_to 'Edit', edit_ct_path(ct) %>
			<%= link_to 'Destroy', ct, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>

</div>

app/views/cts/_form.html.erb
<%= simple_form_for(@ct, html: {class: "form-horizontal"}) do |f| %>
	<%= f.error_notification %>
	<%= f.full_error :image_file_size, class: "alert alert-error" %>
	<%= f.full_error :image_content_type, class: "alert alert-error" %>


  <%= f.input :image, label: "Upload an Image" %>	
  <%= f.input :description, as: :text, input_html: {rows: "5"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cts/edit.html.erb
<h1>Editing ct</h1>

<%= render 'form' %>

<%= link_to 'Show', @ct %> |
<%= link_to 'Back', cts_path %>

app/views/cts/index.html.erb
<%= render 'pages/home' %>

<div id="cts">
    <%= render @cts %>
</div>

app/views/cts/new.html.erb
<h1>New ct</h1>

<%= render 'form' %>

<%= link_to 'Back', cts_path %>

app/views/cts/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @ct.image %>
			<p>
			  <%= @ct.description %>
			</p>
			<p>
			  <%= @ct.user.name %>
			</p>
			<% if current_user == @ct.user %>
				<%= link_to 'Edit', edit_ct_path(@ct) %> |
			<% end %>	
				<%= link_to 'Back', cts_path %>
		</div>	
	</div>	
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		footer footer footer goodness	
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "New App", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
		<ul class="nav">
        	<li><%= link_to "Home", root_path%></li>
			<li><%= link_to "About", about_path%></li>
		</ul>
		
		<ul class="nav pull-right">
			<% if user_signed_in? %>
				<li><%= link_to "New Image", new_ct_path %></li>
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
			<% else %>	
        		<li><%= link_to "Login", new_user_session_path%></li>
			<% end %>	
		</ul>
		
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>New App</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	
	<body>
		<%= render 'layouts/header'%>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>	
			<%= yield %>
			<%= render 'layouts/footer'%>
		</div>
	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>

<div class="hero-unit">
	<p>
		Blah blah blah blizzidy blah.
		This is the member's homepage.
	</p>
</div>

<% else %>	
<div class="hero-unit">
	<h1>Welcome to One Month Rails</h1>
	<p>
		Blah blah blah blizzidy blah.
		This is the homepage.
		<%= link_to "One Month Rails", "http://onemonthrails.com"%>	
	</p>

	<p>
	   <%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn large"%>
	</p>
</div>

<% end %>

app/views/pages/about.html.erb
<h1>About</h1>

<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com"%>
	is a project to teach
	<%= link_to "Ruby on Rails", "http://rubyonrails.org"%>
	in one month.  This is the sample app.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<div class="hero-unit">
	<h1>You're logged in!</h1>
	<p>
		Blah blah blah blizzidy blah.
		This is the member's homepage.
	</p>
</div>

<% else %>	
<div class="hero-unit">
	<h1>Welcome to One Month Rails</h1>
	<p>
		Blah blah blah blizzidy blah.
		This is the homepage.
		<%= link_to "One Month Rails", "http://onemonthrails.com"%>	
	</p>

	<p>
	   <%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn large"%>
	</p>
</div>

<% end %>